using System.Collections;
using UnityEngine;

public class Weapon : MonoBehaviour
{
    public int damage = 10;
    public float fireRate = 0.5f;
    public float range = 8.5f;
    public float bulletSpeed = 10f;
    public int numberOfBullets = 1;
    public int rotationOffset = 0;
    public GameObject bulletPrefab;
    protected GameObject player;
    protected int level = 1;

    private void Start()
    {
        player = GameObject.FindGameObjectWithTag("Player");
        StartCoroutine(Shoot());
    }

    private IEnumerator Shoot()
    {
        while (true)
        {
            yield return new WaitForSeconds(fireRate);
            for (int i = 0; i < numberOfBullets; i++)
            {
                yield return new WaitForSeconds(.05f);
                Fire();
            }
        }
    }

    virtual protected void Fire()
    {
        Vector3 direction = transform.right;
        CreateBullet(direction, false);
    }

    protected GameObject CreateBullet(Vector3 direction, bool rotate)
    {
        Quaternion quaternion = Quaternion.identity;
        if (rotate)
        {
            // Generated by AI
            float angle = Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg + rotationOffset;
            quaternion = Quaternion.AngleAxis(angle, Vector3.forward);
        } 
        GameObject bullet = Instantiate(bulletPrefab, transform.position, quaternion);
        Projectile projectile = bullet.GetComponent<Projectile>();
        projectile.SetDamage(damage);
        projectile.StartCoroutine(projectile.LifeTime(range / bulletSpeed));
        bullet.GetComponent<Rigidbody2D>().velocity = direction.normalized * bulletSpeed;
        return bullet;
    }

    internal void Upgrade()
    {
        level++;
        damage += 2;
        fireRate -= 0.02f;
        if (level % 5 == 0)
        {
            numberOfBullets++;
            range += .1f;
            bulletSpeed += .1f;
        }
    }
}
